### ISSUE TITLE
Cannot install the RcppTOML packages in a CentOS 7.x system

### ISSUE THREAD

**Issue by zhayuan87** [eddelbuettel/rcpptoml#43]
Compiling error for RcppTOML. It seems that there is some C++ code compiling error. I do not know if there is some dependence missing or should I upgrade the C++ compiler.

```
Installing package into ‘/home/zyy/R/x86_64-redhat-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/src/contrib/RcppTOML_0.1.7.tar.gz'
Content type 'application/x-gzip' length 42551 bytes (41 KB)

downloaded 41 KB

* installing *source* package ‘RcppTOML’ ...
** package ‘RcppTOML’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG -I../inst/include/ -DCPPTOML_USE_MAP -I"/home/zyy/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c RcppExports.cpp -o RcppExports.o
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG -I../inst/include/ -DCPPTOML_USE_MAP -I"/home/zyy/R/x86_64-redhat-linux-gnu-library/3.6/Rcpp/include" -I/usr/local/include  -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -c parse.cpp -o parse.o
In file included from parse.cpp:28:0:
../inst/include/toml.hpp: In static member function ‘static std::string includize::toml_spec<char>::unescape_filename(const string&)’:
../inst/include/toml.hpp:29:66: error: no matching function for call to ‘regex_replace(const string&, std::regex, const char [2])’
         return std::regex_replace(str, std::regex("\\\\\""), "\"");
                                                                  ^
../inst/include/toml.hpp:29:66: note: candidates are:
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from ../inst/include/includize.hpp:7,
                 from ../inst/include/toml.hpp:4,
                 from parse.cpp:28:
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class _Ch_type> _Out_iter std::regex_replace(_Out_iter, _Bi_iter, _Bi_iter, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(_Out_iter __out, _Bi_iter __first, _Bi_iter __last,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note:   template argument deduction/substitution failed:
In file included from parse.cpp:28:0:
../inst/include/toml.hpp:29:66: note:   deduced conflicting types for parameter ‘_Bi_iter’ (‘std::basic_regex<char>’ and ‘const char*’)
         return std::regex_replace(str, std::regex("\\\\\""), "\"");
                                                                  ^
In file included from /usr/include/c++/4.8.2/regex:62:0,
                 from ../inst/include/includize.hpp:7,
                 from ../inst/include/toml.hpp:4,
                 from parse.cpp:28:
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note: template<class _Rx_traits, class _Ch_type> std::basic_string<_Ch_type> std::regex_replace(const std::basic_string<_Ch_type>&, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
     regex_replace(const basic_string<_Ch_type>& __s,
     ^
/usr/include/c++/4.8.2/bits/regex.h:2182:5: note:   template argument deduction/substitution failed:
In file included from parse.cpp:28:0:
../inst/include/toml.hpp:29:66: note:   mismatched types ‘const std::basic_string<_Ch_type>’ and ‘const char [2]’
         return std::regex_replace(str, std::regex("\\\\\""), "\"");
                                                                  ^
../inst/include/toml.hpp:30:5: warning: control reaches end of non-void function [-Wreturn-type]
     }
     ^
make: *** [parse.o] Error 1
ERROR: compilation failed for package ‘RcppTOML’
* removing ‘/home/zyy/R/x86_64-redhat-linux-gnu-library/3.6/RcppTOML’
Warning in install.packages :
  installation of package ‘RcppTOML’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/Rtmp8iHCvU/downloaded_packages’
```

Anyone has a clue on this?

Many thanks,

Yuanyuan

**Comment by eddelbuettel** [comment]
Yes. You need a new compiler. The default on CentOS is too old, but you can install what is called `devtoolset` which provides a newer one. The (unrelated, but also for R) package [sparseMatrixStats](https://github.com/const-ae/sparseMatrixStats) has a fairly detailed guide on its README.

**Comment by cihaterdogan** [comment]
Hi, I had the same problem and solved it using the README file mentioned above by **eddelbuettel**. You can find the R code I used below.

`withr::with_makevars(
  new = c(CXX17 = "g++", CXX17FLAGS = "-g -O2 $(LTO)", 
          CXX17PICFLAGS = "-fpic", CXX17STD = "-std=gnu++17"), 
  code = {
    BiocManager::install("RcppTOML")
  })`

**Comment by NathanWycoff** [comment]
@cihaterdogan I can confirm that your fix also works on Ubuntu 22.04. Thanks for saving my morning!

**Comment by eddelbuettel** [comment]
@NathanWycoff You should not need fixes on Ubuntu 22.04 as it current (and I work a fair bit between 22.04 and now 23.04, soon 23.10, myself). 

Exactly what failed, and what of the attributed changes fixed it?

For reference, CRAN is happy on a variety of systems:
![image](https://github.com/eddelbuettel/rcpptoml/assets/673121/d0ce5bb8-2bd7-4056-a5ee-d1ad56ac0bf2)

Trust me that CRAN would let me ASAP if something didn't build...

**Comment by eddelbuettel** [comment]
Demo:

```sh
edd@rob:~/git/rcpptoml(master)$ docker run --rm -ti -v$PWD:/opt -w/opt rocker/r2u:jammy   # Ubuntu 22.04 in current dir
root@6dab1a00fa26:/opt# time installDeps.r      # helper script from 'littler' to install dependencies, here as r2u binaries
* installing deps for *source* package found in current working directory ...
Rcpp (NA -> 1.0.11) [CRAN]
Installing 1 packages: Rcpp
Get:1 http://archive.ubuntu.com/ubuntu jammy InRelease [270 kB]                                                                                                                                                   
Get:2 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3626 B]                                                                                                                               
Ign https://r2u.stat.illinois.edu/ubuntu jammy InRelease                                                                                                                                                          
Get:3 https://r2u.stat.illinois.edu/ubuntu jammy Release [5713 B]                                                                                                                                                 
Get:4 https://r2u.stat.illinois.edu/ubuntu jammy Release.gpg [793 B]                                                                                                                                              
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]                                                                                                                                           
Get:6 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ Packages [43.3 kB]                                                                                                                               
Get:7 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 Packages [2350 kB]                                                                                                                                    
Get:8 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [109 kB]                                                                                                                                         
Get:9 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]                                                                                                                                         
Get:10 https://r2u.stat.illinois.edu/ubuntu jammy/main all Packages [7442 kB]                                                                                                                                     
Get:11 http://archive.ubuntu.com/ubuntu jammy/multiverse amd64 Packages [266 kB]                                                                                                                                  
Get:12 http://archive.ubuntu.com/ubuntu jammy/main amd64 Packages [1792 kB]                                                                                                                                       
Get:13 http://archive.ubuntu.com/ubuntu jammy/restricted amd64 Packages [164 kB]                                                                                                                                  
Get:14 http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages [17.5 MB]                                                                                                                                   
Get:15 http://archive.ubuntu.com/ubuntu jammy-updates/universe amd64 Packages [1255 kB]                                                                                                                           
Get:16 http://archive.ubuntu.com/ubuntu jammy-updates/multiverse amd64 Packages [49.8 kB]                                                                                                                         
Get:17 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 Packages [1235 kB]                                                                                                                               
Get:18 http://archive.ubuntu.com/ubuntu jammy-updates/restricted amd64 Packages [1085 kB]                                                                                                                         
Get:19 http://archive.ubuntu.com/ubuntu jammy-backports/main amd64 Packages [50.3 kB]                                                                                                                             
Get:20 http://archive.ubuntu.com/ubuntu jammy-backports/universe amd64 Packages [28.1 kB]                                                                                                                         
Get:21 http://security.ubuntu.com/ubuntu jammy-security/multiverse amd64 Packages [44.0 kB]                                                                                                                       
Get:22 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [993 kB]                                                                                                                          
Get:23 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [1064 kB]                                                                                                                       
Get:24 http://security.ubuntu.com/ubuntu jammy-security/main amd64 Packages [966 kB]                                                                                                                              
Fetched 36.9 MB in 0s (0 B/s)                                                                                                                                                                                     
Install system packages as root...
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Reading package lists... Done    
Building dependency tree... Done 
Reading state information... Done
Get:1 https://r2u.stat.illinois.edu/ubuntu jammy/main amd64 r-cran-rcpp amd64 1.0.11-1.ca2204.1 [1946 kB]                                                                                                         
Fetched 1946 kB in 0s (0 B/s)                                                                                                                                                                                     
Selecting previously unselected package r-cran-rcpp.
(Reading database ... 18301 files and directories currently installed.)
Preparing to unpack .../r-cran-rcpp_1.0.11-1.ca2204.1_amd64.deb ...
Unpacking r-cran-rcpp (1.0.11-1.ca2204.1) ...
Setting up r-cran-rcpp (1.0.11-1.ca2204.1) ...

real    0m7.672s
user    0m6.075s
sys     0m1.099s
root@6dab1a00fa26:/opt# 
root@6dab1a00fa26:/opt# ./cleanup 
root@6dab1a00fa26:/opt# R CMD INSTALL .
* installing to library ‘/usr/local/lib/R/site-library’
* installing *source* package ‘RcppTOML’ ...
** using staged installation
** libs
using C++ compiler: ‘g++ (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0’
using C++17
g++ -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG -I../inst/include -DTOML_ENABLE_FLOAT16=0 -I'/usr/lib/R/site-library/Rcpp/include'     -fpic  -g -O2 -ffile-prefix-map=/build/r-base-1upgAf/r-base-4.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG -I../inst/include -DTOML_ENABLE_FLOAT16=0 -I'/usr/lib/R/site-library/Rcpp/include'     -fpic  -g -O2 -ffile-prefix-map=/build/r-base-1upgAf/r-base-4.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c parse.cpp -o parse.o
g++ -std=gnu++17 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -o RcppTOML.so RcppExports.o parse.o -L/usr/lib/R/lib -lR
installing to /usr/local/lib/R/site-library/00LOCK-opt/00new/RcppTOML/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (RcppTOML)
root@6dab1a00fa26:/opt# 
```

Also works from CRAN as source if I tell `bspm` to not consider binaries:

```sh
root@6dab1a00fa26:/opt# Rscript -e 'bspm::disable(); install.packages("RcppTOML")'  # from CRAN now as source
Untracing function "install.packages" in package "utils"
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/RcppTOML_0.2.2.tar.gz'
Content type 'application/x-gzip' length 141195 bytes (137 KB)
==================================================
downloaded 137 KB

* installing *source* package ‘RcppTOML’ ...
** package ‘RcppTOML’ successfully unpacked and MD5 sums checked
** using staged installation
** libs
using C++ compiler: ‘g++ (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0’
using C++17
g++ -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG -I../inst/include -DTOML_ENABLE_FLOAT16=0 -I'/usr/lib/R/site-library/Rcpp/include'     -fpic  -g -O2 -ffile-prefix-map=/build/r-base-1upgAf/r-base-4.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++17 -I"/usr/share/R/include" -DNDEBUG -I../inst/include -DTOML_ENABLE_FLOAT16=0 -I'/usr/lib/R/site-library/Rcpp/include'     -fpic  -g -O2 -ffile-prefix-map=/build/r-base-1upgAf/r-base-4.3.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c parse.cpp -o parse.o
g++ -std=gnu++17 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -o RcppTOML.so RcppExports.o parse.o -L/usr/lib/R/lib -lR
installing to /usr/local/lib/R/site-library/00LOCK-RcppTOML/00new/RcppTOML/libs
** R
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** checking absolute paths in shared objects and dynamic libraries
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (RcppTOML)

The downloaded source packages are in
        ‘/tmp/RtmppqHlfS/downloaded_packages’
root@6dab1a00fa26:/opt# 
```

So strictly *no* issues on Ubuntu 22.04 that I can reproduce.

**Comment by NathanWycoff** [comment]
@eddelbuettel  Haha I had the same thought! CRAN is not shy about letting us know when it doesn't like something. Maybe I just have something misconfigured on my system. I'm bad with compilers!

Here is the initial error (the command "g++-7" doesn't seem to exist on my system, which is using g++ 11.4.0 which apt is telling me is up to date):
![image](https://github.com/eddelbuettel/rcpptoml/assets/16657514/8a65fcab-1cef-4683-9848-b2f072ae35a4)

The important part is only setting CXX17 to g++, this worked:

withr::with_makevars( new = c(CXX17 = "g++"),  code = {install.packages("RcppTOML")})

**Comment by NathanWycoff** [comment]
@eddelbuettel Oh I'm seeing it for another package now; it must be on my end. Sorry for the alarm!

**Comment by eddelbuettel** [comment]
Thanks for the follow-up.  I can help diagnose.  (Kinda wrong venue, r-sig-debian list is better but whatevs.)

Start with `g++ --version`.  Which one is your default?

Next, what does R tell you for `R CMD config CXX` ?

**Comment by NathanWycoff** [comment]
@eddelbuettel  Oh, thanks!

Here is the output of those commands:

![image](https://github.com/eddelbuettel/rcpptoml/assets/16657514/5b229061-cc22-47d0-a163-8c3629d83142)

**Comment by eddelbuettel** [comment]
(Let's stop copying pictures where is could be text.)

That seems sufficient.  Please please (as text) show the compiler error from `R CMD INSTALL`

(Though it _is_ unusual so see C++17 hardwired.  Indicates you may have putzed with `~/.R/Makevars`)

**Comment by NathanWycoff** [comment]
@eddelbuettel  indeed I just had a typo in my Makevars! Thanks, and if you're ever in DC, I'll buy you a contextually appropriate beverage.

**Comment by eddelbuettel** [comment]
Thanks for the kind invite.  But too bad -- kiddo #2 just recently left Baltimore for Boston so chances decreasing...

And yes, it is always the small things.  Re-installing a small and cheap package as a litmus + sanity test is good.
