### ISSUE TITLE
can't install on R 3.5.2 ubuntu 14.04

### ISSUE THREAD

**Issue by kuzmenkov111** [eddelbuettel/rcpptoml#31]
Hi!
May help resolve this issue, please?

```
* installing *source* package ‘RcppTOML’ ...
** package ‘RcppTOML’ successfully unpacked and MD5 sums checked
** libs
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I../inst/include/ -DCPPTOML_USE_MAP -I"/usr/local/lib/R/site-library/Rcpp/include" -fpic -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c RcppExports.cpp -o RcppExports.o
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I../inst/include/ -DCPPTOML_USE_MAP -I"/usr/local/lib/R/site-library/Rcpp/include" -fpic -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c parse.cpp -o parse.o
In file included from parse.cpp:28:0:
../inst/include/toml.hpp: In static member function ‘static std::string includize::toml_spec<char>::unescape_filename(const string&)’:
../inst/include/toml.hpp:29:66: error: no matching function for call to ‘regex_replace(const string&, std::regex, const char [2])’
return std::regex_replace(str, std::regex("\\\\\""), "\"");
^
../inst/include/toml.hpp:29:66: note: candidates are:
In file included from /usr/include/c++/4.8/regex:62:0,
from ../inst/include/includize.hpp:7,
from ../inst/include/toml.hpp:4,
from parse.cpp:28:
/usr/include/c++/4.8/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class _Ch_type> _Out_iter std::regex_replace(_Out_iter, _Bi_iter, _Bi_iter, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
regex_replace(_Out_iter __out, _Bi_iter __first, _Bi_iter __last,
^
/usr/include/c++/4.8/bits/regex.h:2162:5: note: template argument deduction/substitution failed:
In file included from parse.cpp:28:0:
../inst/include/toml.hpp:29:66: note: deduced conflicting types for parameter ‘_Bi_iter’ (‘std::basic_regex<char>’ and ‘const char*’)
return std::regex_replace(str, std::regex("\\\\\""), "\"");
^
In file included from /usr/include/c++/4.8/regex:62:0,
from ../inst/include/includize.hpp:7,
from ../inst/include/toml.hpp:4,
from parse.cpp:28:
/usr/include/c++/4.8/bits/regex.h:2182:5: note: template<class _Rx_traits, class _Ch_type> std::basic_string<_Ch_type> std::regex_replace(const std::basic_string<_Ch_type>&, const std::basic_regex<_Ch_type, _Rx_traits>&, const std::basic_string<_Ch_type>&, std::regex_constants::match_flag_type)
regex_replace(const basic_string<_Ch_type>& __s,
^
/usr/include/c++/4.8/bits/regex.h:2182:5: note: template argument deduction/substitution failed:
In file included from parse.cpp:28:0:
../inst/include/toml.hpp:29:66: note: mismatched types ‘const std::basic_string<_Ch_type>’ and ‘const char [2]’
return std::regex_replace(str, std::regex("\\\\\""), "\"");
^
make:
*** [parse.o] Error 1
ERROR: compilation failed for package ‘RcppTOML’
```

**Comment by eddelbuettel** [comment]
Your compiler may be too old  -- which is function of your use of 14.04.

**Comment by mschubert** [comment]
I was just running into the same problem with `Ubuntu=14.04` and `gcc=4.8.2` (not my machine).

The root cause seems to be that while `gcc=4.8.2` in principle supports C++11, it does not support the `regex` module (source: [1](https://stackoverflow.com/a/20534698) and [2](https://github.com/Corvusoft/restbed/issues/328)).

Could you maybe amend the package `DESCRIPTION` that in fact `gcc>=4.9` is required for compiling `RcppTOML`?

**Comment by eddelbuettel** [comment]
See what I do in [Travis CI setup](https://github.com/eddelbuettel/rcpptoml/blob/master/.travis.yml) by bringing in more recent compilers.

The [DESCRIPTION](https://github.com/eddelbuettel/rcpptoml/blob/master/DESCRIPTION) states "modern C++11" as a requirement, I will remove "modern" here as  this is now standard.   I can roll the >= for `g++` to 4.9.3 as that is the equally outdated version used by CRAN on Windows.

Besides that, I am afraid, there is little I can do for you if you really have to run 14.04.  You may want to look into other TOML client libraries.

**Comment by eddelbuettel** [comment]
Done and done in 5a7fec4

**Comment by HenrikBengtsson** [comment]
I can confirm this on CentOS 7: RcppTOML fails to compile with g++ 4.8.5 (20150623), but installs with g++ 5.3.1 (20160406) from scl-devtoolset-4.  Sorry, don't have a g++ 4.9.x to try with.

**Comment by eddelbuettel** [comment]
Yes, kinda known, documented and old news.  CentOS is really pretty terrible that with its _default_ binaries.  Emacs 24 for example.  We use CentOS 7.3 with gcc/g++ 7.* at work.  Which, by the wonders of RH, is a supported-but-extra-install option.  

In short, only 4.9.* _sort of_ brings C++11 and enough of the C++11 libraries, 5.* is better and 2019 just called and reminded us that gcc/g++ 9.* are current.
